version: '3.8'

services:
  backend:
    build: 
      context: backend-service
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
  frontend:
    build: 
      context: frontend-service
      dockerfile: Dockerfile
    ports:
      - '3000:5000'