version: '3.8'

services:
  backend:
    build: 
      context: backend-service
      dockerfile: Dockerfile
    image: jtwizeyimana/devops-exam-backend 
    ports:
      - '5000:5000'    
    links:
      - "database"
  frontend:
    build: 
      context: frontend-service
      dockerfile: Dockerfile
    image: jtwizeyimana/devops-exam-frontend 
    ports:
      - '8080:80'
  database:
    build:
      context: database
      dockerfile: Dockerfile    
    image: "jtwizeyimana/devops-exam-db"
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  
  nginx:
    build: 
      context: nginx
      dockerfile: Dockerfile 
    image: "jtwizeyimana/devops-exam-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
volumes:
  db: