name: Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16.14.1]
    steps:
      - uses: actions/checkout@v3
      - name: Change directory
        run: cd frontend-service
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: npm install
      - name: lint
        run: npm lint
      - name: build
        run: npm build