name: Docker integration

on:
  push:
    branches:
      - 'exam'
  pull_request:
    branches:
      - 'exam'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push frontend
        uses: docker/build-push-action@v2
        run: ls
        with:
          context: "{{defaultContext}}:frontend-service"
          push: true
          tags: jtwizeyimana/devops-exam-frontend:latest
      -      
        name: Build and push backend
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:backend-service"
          push: true
          tags: jtwizeyimana/devops-exam-backend:latest